import type { Metadata } from 'next';
import Link from 'next/link';
import { PageHeader, PageShell } from '@/components/layout/PageHeader';
import { Card, CardTitle } from '@/components/ui/Card';
import { branding } from '@/lib/config/branding';

export const metadata: Metadata = {
  title: 'About',
  description: `What ${branding.productName} is, and what it deliberately does not claim.`,
};

export default function AboutPage() {
  return (
    <PageShell>
      <PageHeader
        eyebrow="About"
        title={branding.productName}
        lede={branding.description}
      />

      <Card className="flex flex-col gap-3">
        <CardTitle>What this is</CardTitle>
        <p className="text-[var(--color-text-secondary)]">
          A tool for one question that is hard to answer by reading straight through: who
          was alive at the same time? Genealogies give ages and intervals, and working out
          what those imply is arithmetic nobody wants to do by hand.
        </p>
      </Card>

      <Card className="flex flex-col gap-3">
        <CardTitle>What it does not claim</CardTitle>
        <ul className="flex list-disc flex-col gap-2 pl-5 text-[var(--color-text-secondary)]">
          <li>
            It does not claim the years are dates in any calendar. They are counted from a
            fixed starting point so that intervals can be compared.
          </li>
          <li>It does not claim two people met because their lifetimes overlapped.</li>
          <li>
            It does not fill gaps. Where the text gives no age, the app says so rather
            than estimating.
          </li>
          <li>
            It does not settle interpretive disagreements. Where readings differ, both are
            shown and the difference is labelled.
          </li>
        </ul>
      </Card>

      <Card className="flex flex-col gap-3">
        <CardTitle>Where the numbers come from</CardTitle>
        <p className="text-[var(--color-text-secondary)]">
          Every figure was read from the biblical text by a person and recorded with the
          verse it came from. Nothing in the dataset was generated by a language model,
          and no date, lifespan, relationship or reference was inferred to fill a gap.
        </p>
        <p>
          <Link
            href="/chronology"
            className="rounded underline underline-offset-4 hover:text-[var(--color-accent)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-accent)]"
          >
            How the dates work
          </Link>
        </p>
      </Card>
    </PageShell>
  );
}
