import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, Info, ShieldCheck } from 'lucide-react';
import { PageHeader, PageShell } from '@/components/layout/PageHeader';
import { Card, CardTitle } from '@/components/ui/Card';
import { branding } from '@/lib/config/branding';

export const metadata: Metadata = {
  title: 'About',
  description: `What ${branding.productName} is, and what it deliberately does not claim.`,
};

export default function AboutPage() {
  return (
    <PageShell>
      <PageHeader
        eyebrow="Project Scope"
        title={branding.productName}
        icon={<Info className="size-4" />}
        lede={branding.description}
      />

      <Card className="glass-panel flex flex-col gap-3 rounded-2xl p-6 shadow-md">
        <CardTitle className="text-xl">What this is</CardTitle>
        <p className="text-[var(--color-text-secondary)] leading-relaxed">
          A tool for one question that is hard to answer by reading straight through: who
          was alive at the same time? Genealogies give ages and intervals, and working out
          what those imply is arithmetic nobody wants to do by hand.
        </p>
      </Card>

      <Card className="glass-panel flex flex-col gap-3 rounded-2xl p-6 shadow-md border-l-4 border-l-amber-400">
        <CardTitle className="text-xl">What it deliberately does not claim</CardTitle>
        <ul className="flex flex-col gap-2.5 text-sm text-[var(--color-text-secondary)] leading-relaxed">
          <li className="flex items-start gap-2">
            <span className="size-1.5 rounded-full bg-[var(--color-accent)] mt-2 shrink-0" />
            <span>
              It does not claim the years are dates in any calendar. They are counted from
              a fixed starting point so that intervals can be compared.
            </span>
          </li>
          <li className="flex items-start gap-2">
            <span className="size-1.5 rounded-full bg-[var(--color-accent)] mt-2 shrink-0" />
            <span>
              It does not claim two people met because their lifetimes overlapped.
            </span>
          </li>
          <li className="flex items-start gap-2">
            <span className="size-1.5 rounded-full bg-[var(--color-accent)] mt-2 shrink-0" />
            <span>
              It does not fill gaps. Where the text gives no age, the app says so rather
              than estimating.
            </span>
          </li>
          <li className="flex items-start gap-2">
            <span className="size-1.5 rounded-full bg-[var(--color-accent)] mt-2 shrink-0" />
            <span>
              It does not settle interpretive disagreements. Where readings differ, both
              are shown and the difference is labelled.
            </span>
          </li>
        </ul>
      </Card>

      <Card className="glass-panel flex flex-col gap-4 rounded-2xl p-6 shadow-md">
        <div className="flex items-center gap-2">
          <ShieldCheck className="size-5 text-emerald-400" />
          <CardTitle className="text-xl">Where the numbers come from</CardTitle>
        </div>
        <p className="text-[var(--color-text-secondary)] leading-relaxed text-sm">
          Every figure was read from the biblical text by a person and recorded with the
          verse it came from. Nothing in the dataset was generated by a language model,
          and no date, lifespan, relationship or reference was inferred to fill a gap.
        </p>
        <div>
          <Link
            href="/chronology"
            className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[var(--color-surface-overlay)] border border-[var(--color-border-subtle)] px-4 font-semibold text-sm hover:border-[var(--color-accent)] hover:text-[var(--color-accent)] transition-colors focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-accent)]"
          >
            <span>Learn how the dates work</span>
            <ArrowRight className="size-4" />
          </Link>
        </div>
      </Card>
    </PageShell>
  );
}
