import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import {
  ALTERNATE_CHRONOLOGY_ID,
  DEFAULT_CHRONOLOGY_ID,
} from '../lib/config/chronology-defaults';
import type { EventChronology, PersonChronology, Relationship } from '../lib/domain';
import { validateDerived } from '../lib/validation/validate-derived';
import type { Finding } from '../lib/validation/validate-dataset';

/**
 * Validates the derived chronology and writes the integrity report.
 *
 * Runs after scripts/derive-chronology.ts, which produces the files this
 * reads. A severe finding exits non-zero, so a chronology that contradicts
 * itself fails the build (requirement section 21).
 */
const CANONICAL = join(process.cwd(), 'data', 'canonical');
const GENERATED = join(process.cwd(), 'data', 'generated');

async function read<T>(dir: string, name: string): Promise<T> {
  return JSON.parse(await readFile(join(dir, name), 'utf8')) as T;
}

interface Section {
  chronologyId: string;
  findings: Finding[];
  records: PersonChronology[];
  events: EventChronology[];
}

async function check(chronologyId: string, refs: Set<string>): Promise<Section> {
  const records = await read<PersonChronology[]>(
    GENERATED,
    `person-chronology.${chronologyId}.json`,
  );
  const events = await read<EventChronology[]>(
    GENERATED,
    `event-chronology.${chronologyId}.json`,
  );
  const relationships = await read<Relationship[]>(CANONICAL, 'relationships.json');

  return {
    chronologyId,
    records,
    events,
    findings: validateDerived({
      chronologyId,
      records,
      events,
      relationships,
      referenceIds: refs,
    }),
  };
}

function summarise(section: Section): string[] {
  const { records, events } = section;
  const dated = records.filter((r) => r.birthYear !== null);
  const count = (field: 'birthConfidence' | 'lifespanConfidence') => {
    const tally = new Map<string, number>();
    for (const r of records) tally.set(r[field], (tally.get(r[field]) ?? 0) + 1);
    return [...tally.entries()]
      .sort()
      .map(([k, v]) => `${k} ${v}`)
      .join(', ');
  };

  const years = dated.map((r) => r.birthYear as number);
  const span =
    years.length > 0 ? `${Math.min(...years)} to ${Math.max(...years)} AM` : 'none';

  return [
    `### ${section.chronologyId}`,
    '',
    `- People: ${records.length}, of which ${dated.length} have a birth year`,
    `- Birth confidence: ${count('birthConfidence')}`,
    `- Lifespan confidence: ${count('lifespanConfidence')}`,
    `- Birth years span: ${span}`,
    `- Events: ${events.length}, of which ${events.filter((e) => e.startYear !== null).length} are dated`,
    `- Findings: ${section.findings.filter((f) => f.severity === 'severe').length} severe, ${section.findings.filter((f) => f.severity === 'warning').length} warning`,
    '',
  ];
}

function renderFindings(findings: Finding[]): string[] {
  if (findings.length === 0) return ['No findings.', ''];

  const lines = ['| Severity | Check | Subject | Detail |', '| --- | --- | --- | --- |'];
  for (const f of findings) {
    lines.push(`| ${f.severity} | ${f.check} | ${f.subject} | ${f.message} |`);
  }
  lines.push('');
  return lines;
}

async function main() {
  const references = await read<Array<{ id: string }>>(
    CANONICAL,
    'scripture-references.json',
  );
  const refs = new Set(references.map((r) => r.id));

  const sections: Section[] = [];
  for (const chronologyId of [DEFAULT_CHRONOLOGY_ID, ALTERNATE_CHRONOLOGY_ID]) {
    sections.push(await check(chronologyId, refs));
  }

  const all = sections.flatMap((s) => s.findings);
  const severe = all.filter((f) => f.severity === 'severe');
  const warnings = all.filter((f) => f.severity === 'warning');

  const report = [
    '# Dataset integrity report',
    '',
    'Generated by `npm run validate:derived`. Not committed: it describes the',
    'derived chronology, which is itself recomputed on every build.',
    '',
    `**${severe.length} severe, ${warnings.length} warning.**`,
    '',
    '## Per chronology',
    '',
    ...sections.flatMap(summarise),
    '## Findings',
    '',
    ...renderFindings(all),
  ].join('\n');

  await mkdir(GENERATED, { recursive: true });
  await writeFile(join(GENERATED, 'INTEGRITY_REPORT.md'), `${report}\n`, 'utf8');

  for (const section of sections) {
    console.log(
      `\n${section.chronologyId}: ${section.records.length} people, ` +
        `${section.findings.filter((f) => f.severity === 'severe').length} severe, ` +
        `${section.findings.filter((f) => f.severity === 'warning').length} warning.`,
    );
  }

  if (warnings.length > 0) {
    console.log('\nWARNINGS — reported, do not fail the build');
    for (const f of warnings) console.log(`  ${f.check} ${f.subject}: ${f.message}`);
  }
  if (severe.length > 0) {
    console.error('\nSEVERE — these fail the build');
    for (const f of severe) console.error(`  ${f.check} ${f.subject}: ${f.message}`);
    console.error(`\n${severe.length} severe finding(s). Derived data is invalid.`);
    process.exit(1);
  }

  console.log(
    `\nDerived chronology validation passed. Report: data/generated/INTEGRITY_REPORT.md`,
  );
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
