-- 0011 — Content: generated discoveries, quiz templates, learning journeys,
-- achievement definitions. Public read, service-role write.

-- Machine-generated by the discovery engine from verified data. Rows are a
-- cache with a stable id for share URLs, regenerated rather than edited. An
-- LLM never decides whether a discovery is true (requirement section 34).
CREATE TABLE IF NOT EXISTS discoveries (
  id             text PRIMARY KEY,
  discovery_type text NOT NULL,
  chronology_id  text NOT NULL REFERENCES chronologies(id),
  payload        jsonb NOT NULL,
  person_ids     text[] NOT NULL DEFAULT '{}',
  generated_at   timestamptz NOT NULL DEFAULT now()
);

-- Templates and parameters, never answers. Answers are produced by the
-- chronology engine at generation time and validated against it
-- (Phase 12 exit gate).
CREATE TABLE IF NOT EXISTS quiz_questions (
  id            text PRIMARY KEY,
  mode          text NOT NULL,
  template      text NOT NULL,
  parameters    jsonb NOT NULL DEFAULT '{}'::jsonb,
  difficulty    integer NOT NULL DEFAULT 1 CHECK (difficulty BETWEEN 1 AND 5),
  review_status review_status NOT NULL DEFAULT 'DRAFT'
);

SELECT public.add_audit_columns('quiz_questions');

CREATE TABLE IF NOT EXISTS learning_paths (
  id            text PRIMARY KEY,
  name          text NOT NULL,
  slug          text NOT NULL UNIQUE,
  description   text,
  sort_order    integer NOT NULL DEFAULT 0,
  review_status review_status NOT NULL DEFAULT 'DRAFT'
);

SELECT public.add_audit_columns('learning_paths');

CREATE TABLE IF NOT EXISTS learning_path_steps (
  id               bigserial PRIMARY KEY,
  learning_path_id text NOT NULL REFERENCES learning_paths(id) ON DELETE CASCADE,
  step_order       integer NOT NULL,
  title            text NOT NULL,
  body             text,
  person_id        text REFERENCES people(id) ON DELETE SET NULL,
  event_id         text REFERENCES events(id) ON DELETE SET NULL,
  quiz_question_id text REFERENCES quiz_questions(id) ON DELETE SET NULL,
  UNIQUE (learning_path_id, step_order)
);

CREATE TABLE IF NOT EXISTS achievements (
  id          text PRIMARY KEY,
  name        text NOT NULL,
  description text NOT NULL,
  icon        text,
  sort_order  integer NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS discoveries_by_type
  ON discoveries (chronology_id, discovery_type);
CREATE INDEX IF NOT EXISTS discoveries_by_person ON discoveries USING gin (person_ids);

-- Deferred foreign keys: these targets did not exist when the referring tables
-- were created in 0010.
DO $$ BEGIN
  ALTER TABLE quiz_attempts
    ADD CONSTRAINT quiz_attempts_question_fk
    FOREIGN KEY (question_id) REFERENCES quiz_questions(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE user_achievements
    ADD CONSTRAINT user_achievements_achievement_fk
    FOREIGN KEY (achievement_id) REFERENCES achievements(id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

SELECT public.apply_canonical_rls('discoveries', false);
SELECT public.apply_canonical_rls('quiz_questions', true);
SELECT public.apply_canonical_rls('learning_paths', true);
SELECT public.apply_canonical_rls('learning_path_steps', false);
SELECT public.apply_canonical_rls('achievements', false);
